# Generated by Django 4.0.4 on 2022-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_pontuacaoquizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='pontuacao',
            field=models.IntegerField(),
        ),
    ]
