# Generated by Django 4.0.4 on 2022-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_pontuacaoquizz_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pergunta1', models.IntegerField(default=0)),
                ('pergunta2', models.IntegerField(default=0)),
                ('pergunta3', models.IntegerField(default=0)),
                ('pergunta4', models.CharField(max_length=50)),
                ('pergunta5', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
