# Generated by Django 4.0.4 on 2022-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_quizz_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='pergunta1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='pergunta5',
            field=models.CharField(max_length=50),
        ),
    ]
