# Generated by Django 4.0.4 on 2022-05-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_noticias_alter_projetos_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='participantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
    ]
