# Generated by Django 4.0.4 on 2022-05-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_noticias_imagem_remove_projetos_participantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesCurriculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('topicos', models.CharField(max_length=2000)),
                ('linkUC', models.URLField(blank=True)),
                ('professores', models.ManyToManyField(to='portfolio.pessoa')),
                ('projetos', models.ManyToManyField(blank=True, to='portfolio.projetos')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
