# Generated by Django 4.0.4 on 2022-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_unidadescurriculares_delete_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadescurriculares',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidadescurriculares',
            name='semestre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
    ]
