# Generated by Django 4.0.4 on 2022-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_unidadescurriculares_ano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('imagem', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='unidadescurriculares',
            name='professores',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='unidadescurriculares',
            name='topicos',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
