# Generated by Django 4.0.4 on 2022-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_noticias_alter_unidadescurriculares_professores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
