# Generated by Django 4.0.4 on 2022-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_noticias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descricao',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
