# Generated by Django 4.0.4 on 2022-05-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_noticias_descricao_alter_noticias_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('acronimo', models.CharField(max_length=200)),
                ('ano', models.IntegerField(default=0)),
                ('criador', models.CharField(blank=True, max_length=200)),
                ('logotipo', models.ImageField(null=True, upload_to='media/')),
                ('link', models.URLField(blank=True)),
                ('caracteristicas', models.CharField(max_length=200)),
            ],
        ),
    ]
