# Generated by Django 4.0.4 on 2022-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_padroes_tecnologias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='padroes',
            name='descricao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='padroes',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
