# Generated by Django 4.0.4 on 2022-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_tecnicas_padroes_descricao_padroes_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='padroes',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tecnicas',
            name='imagem',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
