# Generated by Django 4.0.4 on 2022-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_delete_pontuacaoquizz_alter_noticias_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhosFinaisCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(max_length=200)),
                ('orientadores', models.CharField(max_length=200)),
                ('ano', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(max_length=500)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('relatorio', models.CharField(max_length=1000)),
                ('github', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='acronimo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
