# Generated by Django 4.0.4 on 2022-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_trabalhosfinaiscurso_alter_tecnologias_acronimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhosfinaiscurso',
            name='relatorio',
            field=models.URLField(blank=True),
        ),
    ]
