# Generated by Django 4.0.4 on 2022-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_trabalhosfinaiscurso_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologias',
            name='onde',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
