# Generated by Django 4.0.4 on 2022-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_tecnologias_onde_alter_tecnologias_caracteristicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiasInteressantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('acronimo', models.CharField(blank=True, max_length=200)),
                ('ano', models.IntegerField(default=0)),
                ('criador', models.CharField(blank=True, max_length=200)),
                ('logotipo', models.ImageField(null=True, upload_to='media/')),
                ('link', models.URLField(blank=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
